### ISSUE TITLE
Feature Idea:  Reporting of Playlist Duplicates

### ISSUE THREAD

**Issue by mgillespie** [soulfx/gmusic-playlist#11]
As a user, I would like to have the report include details within each playlist, of duplicate artist and track titles.   It's currently very easy to inadvertently add a duplicates on Google Music.

**Comment by soulfx** [comment]
duplicate detection and handling has been added and is enabled by default.  when importing and exporting playlists, duplicate songs will be detected, identified, and will not be added to or exported from the playlist. see 6a630df5973b185de27b95cc2fb4293a614e0f4d

**Comment by Suncatcher** [comment]
@soulfx, by the way, it is cool feature but how we can see the duplicates? I have these lines in my report

    530/531 tracks imported
    ! 0.0% of tracks could not be matched
    - 0.564971751412% of tracks had low match scores
    {T} 1 low matches were due to a song title mismatch
    {A} 1 low matches were due to song artist mismatch
    {D} 1 duplicates were found and skipped
    + 99.4350282486% of tracks had high match scores

How can I see which track was counted as duplicate? It is very cumbersome to check all 530 track to reveal this.
