### ISSUE TITLE
Error 'IndexError: list index out of range'

### ISSUE THREAD

**Issue by rudiiistarrr** [soulfx/gmusic-playlist#25]
Hello i'm trying to import a playlist and i always get the following error:

Traceback (most recent call last):
  File "ImportList.py", line 221, in <module>
    details = create_details(details_list)
  File "C:\common.py", line 87, in create_details
    details[track_info_order[pos]] = nfo.strip()
IndexError: list index out of range

**Comment by soulfx** [comment]
hello,

i'll take a look at a few edge cases that can cause the issue.  can you send me the playlist file you are getting the error on?

**Comment by mjt60** [comment]
I am also receiving this error whilst attempting to import around 1800 songs in the following format.

Seaside\The Kooks\Inside In / Inside Out
Crazy - single version\Gnarls Barkley\Crazy
Keep On Callin' Ft Akon\P-Money, Akon\Magic City

===============================================================
Searching for songs from: songs
===============================================================
Traceback (most recent call last):
  File "ImportList.py", line 221, in <module>
    details = create_details(details_list)
  File "/Users/Matti/Downloads/gmusic-playlist/common.py", line 87, in create_details
    details[track_info_order[pos]] = nfo.strip()
IndexError: list index out of range

**Comment by soulfx** [comment]
the separator char was defaulted to comma in the last update in order to more closely match the csv standard.  since the playlist you have uses the old \ separator, have you changed the separator character back to \  in the settings  ?

**Comment by mjt60** [comment]
Thanks @soulfx, that was it! You legend.
