### ISSUE TITLE
Newbie help on "ImportError: No module named gmusicapi"

### ISSUE THREAD

**Issue by angadchawla** [soulfx/gmusic-playlist#29]
Hi,

I am a newbie at Python and I don't know a lot. I am using this guide (https://www.reddit.com/r/spotify/comments/35dgmj/instructions_to_import_music_from_spotify_into/) to transfer my music playlist from Spotify to Google Music. I am at the last step and I am getting this problem.

`Angads-MacBook-Pro:gmusic-playlist-master Angad$ python ImportList.py ~/Desktop/Spotify.txt`
`Traceback (most recent call last):`
 `File "ImportList.py", line 8, in <module>
    from common import *`
 `File "/Users/Angad/Downloads/gmusic-playlist-master/common.py", line 5, in <module>
   from gmusicapi import Mobileclient`
`ImportError: No module named gmusicapi`

I know that you have talked about this in another thread, but I could not understand an easy solution to this. 

I hope that you can help me with this. Otherwise I am going to have to gruel though transferring my playlist song by song. :grin:

**Comment by soulfx** [comment]
gmusicapi can be installed either with pip or via the setup.py script.  the setup.py script is what i use to install gmusicapi, but pip should also work.
`$ pip install gmusicapi` to install via pip. you should be able to run this in any directory.  if you don't have pip installed, check out instructions at https://pip.pypa.io/en/latest/installing/
`$ python setup.py install` to install with setup.py script. you'll be running this in the gmusicapi directory.

**Comment by angadchawla** [comment]
`gmusic-playlist-master Angad$ python setup.py install
python: can't open file 'setup.py': [Errno 2] No such file or directory`

Where do I get the setup.py file?

**Comment by soulfx** [comment]
you'll need to download the gmsuicapi source at https://github.com/simon-weber/gmusicapi and run `python setup.py install` from within the downloaded gmusicapi source directory.

**Comment by angadchawla** [comment]
Also when I did pip install I am getting this:

Angads-MacBook-Pro:gmusic-playlist-master Angad$ sudo -H pip install gmusicapi
Password:
Collecting gmusicapi
  Downloading gmusicapi-7.0.0.tar.gz (147kB)
    100% |████████████████████████████████| 151kB 184kB/s
Collecting validictory!=0.9.2,>=0.8.0 (from gmusicapi)
  Downloading validictory-1.0.1-py2.py3-none-any.whl
Collecting decorator>=3.3.1 (from gmusicapi)
  Downloading decorator-4.0.4-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): mutagen>=1.18 in /Library/Python/2.7/site-packages (from gmusicapi)
Collecting protobuf>=2.4.1 (from gmusicapi)
  Downloading protobuf-2.6.1.tar.gz (188kB)
    100% |████████████████████████████████| 188kB 685kB/s
Collecting requests!=1.2.0,!=2.2.1,>=1.1.0 (from gmusicapi)
  Downloading requests-2.8.1-py2.py3-none-any.whl (497kB)
    100% |████████████████████████████████| 499kB 775kB/s
Requirement already satisfied (use --upgrade to upgrade): python-dateutil!=2.0,>=1.3 in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from gmusicapi)
Collecting proboscis>=1.2.5.1 (from gmusicapi)
  Downloading proboscis-1.2.6.0.tar.gz
Collecting oauth2client>=1.1 (from gmusicapi)
  Downloading oauth2client-1.5.2.tar.gz (56kB)
    100% |████████████████████████████████| 57kB 2.2MB/s
Collecting mock>=0.7.0 (from gmusicapi)
  Downloading mock-1.3.0-py2.py3-none-any.whl (56kB)
    100% |████████████████████████████████| 57kB 2.7MB/s
Collecting appdirs>=1.1.0 (from gmusicapi)
  Downloading appdirs-1.4.0-py2.py3-none-any.whl
Collecting gpsoauth==0.0.4 (from gmusicapi)
  Downloading gpsoauth-0.0.4.tar.gz
Collecting MechanicalSoup (from gmusicapi)
  Downloading MechanicalSoup-0.4.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): pyopenssl in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from gmusicapi)
Collecting ndg-httpsclient (from gmusicapi)
  Downloading ndg_httpsclient-0.4.0.tar.gz
Requirement already satisfied (use --upgrade to upgrade): pyasn1 in /Library/Python/2.7/site-packages (from gmusicapi)
Requirement already satisfied (use --upgrade to upgrade): setuptools in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from protobuf>=2.4.1->gmusicapi)
Collecting httplib2>=0.9.1 (from oauth2client>=1.1->gmusicapi)
  Downloading httplib2-0.9.2.tar.gz (205kB)
    100% |████████████████████████████████| 208kB 2.2MB/s
Collecting pyasn1-modules>=0.0.5 (from oauth2client>=1.1->gmusicapi)
  Downloading pyasn1_modules-0.0.8-py2.py3-none-any.whl
Collecting rsa>=3.1.4 (from oauth2client>=1.1->gmusicapi)
  Downloading rsa-3.2.3-py2.py3-none-any.whl (44kB)
    100% |████████████████████████████████| 45kB 2.5MB/s
Collecting six>=1.6.1 (from oauth2client>=1.1->gmusicapi)
  Downloading six-1.10.0-py2.py3-none-any.whl
Collecting funcsigs (from mock>=0.7.0->gmusicapi)
  Downloading funcsigs-0.4-py2.py3-none-any.whl
Collecting pbr>=0.11 (from mock>=0.7.0->gmusicapi)
  Downloading pbr-1.8.1-py2.py3-none-any.whl (89kB)
    100% |████████████████████████████████| 90kB 1.7MB/s
Collecting pycrypto (from gpsoauth==0.0.4->gmusicapi)
  Downloading pycrypto-2.6.1.tar.gz (446kB)
    100% |████████████████████████████████| 446kB 670kB/s
Collecting beautifulsoup4 (from MechanicalSoup->gmusicapi)
  Downloading beautifulsoup4-4.4.1-py2-none-any.whl (81kB)
    100% |████████████████████████████████| 81kB 1.1MB/s
Building wheels for collected packages: gmusicapi, protobuf, proboscis, oauth2client, gpsoauth, ndg-httpsclient, httplib2, pycrypto
  Running setup.py bdist_wheel for gmusicapi
  Stored in directory: /var/root/Library/Caches/pip/wheels/bf/77/9d/ff67f86a69133a89cd9d6adb81297a850b018c0b22ed5e2d92
  Running setup.py bdist_wheel for protobuf
  Stored in directory: /var/root/Library/Caches/pip/wheels/2c/40/46/9dc67b28cbea4b3c9752dde3abd4787d96c318a5292af8c1de
  Running setup.py bdist_wheel for proboscis
  Stored in directory: /var/root/Library/Caches/pip/wheels/db/dc/63/9e3ef983583fd3674c751b188bfd45e8dd19ccf933da266fff
  Running setup.py bdist_wheel for oauth2client
  Stored in directory: /var/root/Library/Caches/pip/wheels/79/9e/56/e82aa05430ac46bd675b90e030d09d567cd29a524ff9ce1a67
  Running setup.py bdist_wheel for gpsoauth
  Stored in directory: /var/root/Library/Caches/pip/wheels/95/39/03/faa2ab3c3cd8491dda600a95962e04456bdadba5ccb09fe667
  Running setup.py bdist_wheel for ndg-httpsclient
  Stored in directory: /var/root/Library/Caches/pip/wheels/30/85/40/a29750f9287fe119a10708580a73cfb16f51e5f9a820430a2d
  Running setup.py bdist_wheel for httplib2
  Stored in directory: /var/root/Library/Caches/pip/wheels/e1/a3/05/e66aad1380335ee0a823c8f1b9006efa577236a24b3cb1eade
  Running setup.py bdist_wheel for pycrypto
  Stored in directory: /var/root/Library/Caches/pip/wheels/96/b0/e6/03e439d41cb2592b5c4c9c77873761d6cbd417b332076680cd
Successfully built gmusicapi protobuf proboscis oauth2client gpsoauth ndg-httpsclient httplib2 pycrypto
Installing collected packages: validictory, decorator, protobuf, requests, proboscis, httplib2, pyasn1-modules, rsa, six, oauth2client, funcsigs, pbr, mock, appdirs, pycrypto, ndg-httpsclient, gpsoauth, beautifulsoup4, MechanicalSoup, gmusicapi
  Found existing installation: six 1.4.1
    DEPRECATION: Uninstalling a distutils installed project (six) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling six-1.4.1:
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip/basecommand.py", line 211, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip/commands/install.py", line 311, in run
    root=options.root_path,
  File "/Library/Python/2.7/site-packages/pip/req/req_set.py", line 640, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 716, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip/req/req_uninstall.py", line 125, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip/utils/__init__.py", line 315, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/tmp/pip-6HB9SD-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'
Angads-MacBook-Pro:gmusic-playlist-master Angad$ python ImportList.py ~/Desktop/Spotify.txt
Traceback (most recent call last):
  File "ImportList.py", line 8, in <module>
    from common import *
  File "/Users/Angad/Downloads/gmusic-playlist-master/common.py", line 5, in <module>
    from gmusicapi import Mobileclient
ImportError: No module named gmusicapi/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from gmusicapi)
Requirement already satisfied (use --upgrade to upgrade): pyopenssl in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from gmusicapi)
Collecting pyasn1 (from gmusicapi)
  Downloading pyasn1-0.1.9-py2.py3-none-any.whl
Collecting mutagen>=1.18 (from gmusicapi)
Collecting gpsoauth==0.0.4 (from gmusicapi)
Collecting mock>=0.7.0 (from gmusicapi)
  Downloading mock-1.3.0-py2.py3-none-any.whl (56kB)
    100% |████████████████████████████████| 57kB 733kB/s
Collecting proboscis>=1.2.5.1 (from gmusicapi)
Collecting ndg-httpsclient (from gmusicapi)
Collecting oauth2client>=1.1 (from gmusicapi)
Collecting appdirs>=1.1.0 (from gmusicapi)
  Downloading appdirs-1.4.0-py2.py3-none-any.whl
Collecting MechanicalSoup (from gmusicapi)
  Downloading MechanicalSoup-0.4.0-py2.py3-none-any.whl
Collecting validictory!=0.9.2,>=0.8.0 (from gmusicapi)
  Downloading validictory-1.0.1-py2.py3-none-any.whl
Collecting requests!=1.2.0,!=2.2.1,>=1.1.0 (from gmusicapi)
  Downloading requests-2.8.1-py2.py3-none-any.whl (497kB)
    100% |████████████████████████████████| 499kB 312kB/s
Collecting protobuf>=2.4.1 (from gmusicapi)
Collecting decorator>=3.3.1 (from gmusicapi)
  Downloading decorator-4.0.4-py2.py3-none-any.whl
Collecting pycrypto (from gpsoauth==0.0.4->gmusicapi)
Collecting funcsigs (from mock>=0.7.0->gmusicapi)
  Downloading funcsigs-0.4-py2.py3-none-any.whl
Collecting pbr>=0.11 (from mock>=0.7.0->gmusicapi)
  Downloading pbr-1.8.1-py2.py3-none-any.whl (89kB)
    100% |████████████████████████████████| 90kB 1.7MB/s
Collecting six>=1.7 (from mock>=0.7.0->gmusicapi)
  Downloading six-1.10.0-py2.py3-none-any.whl
Collecting pyasn1-modules>=0.0.5 (from oauth2client>=1.1->gmusicapi)
  Downloading pyasn1_modules-0.0.8-py2.py3-none-any.whl
Collecting rsa>=3.1.4 (from oauth2client>=1.1->gmusicapi)
  Downloading rsa-3.2.3-py2.py3-none-any.whl (44kB)
    100% |████████████████████████████████| 45kB 2.2MB/s
Collecting httplib2>=0.9.1 (from oauth2client>=1.1->gmusicapi)
Collecting beautifulsoup4 (from MechanicalSoup->gmusicapi)
  Downloading beautifulsoup4-4.4.1-py2-none-any.whl (81kB)
    100% |████████████████████████████████| 81kB 3.5MB/s
Requirement already satisfied (use --upgrade to upgrade): setuptools in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from protobuf>=2.4.1->gmusicapi)
Installing collected packages: pyasn1, mutagen, pycrypto, requests, ndg-httpsclient, gpsoauth, funcsigs, pbr, six, mock, proboscis, pyasn1-modules, rsa, httplib2, oauth2client, appdirs, beautifulsoup4, MechanicalSoup, validictory, protobuf, decorator, gmusicapi
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip/basecommand.py", line 211, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip/commands/install.py", line 311, in run
    root=options.root_path,
  File "/Library/Python/2.7/site-packages/pip/req/req_set.py", line 646, in install
    **kwargs
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 803, in install
    self.move_wheel_files(self.source_dir, root=root)
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 998, in move_wheel_files
    isolated=self.isolated,
  File "/Library/Python/2.7/site-packages/pip/wheel.py", line 371, in move_wheel_files
    clobber(source, dest, False, fixer=fixer, filter=filter)
  File "/Library/Python/2.7/site-packages/pip/wheel.py", line 310, in clobber
    ensure_dir(destdir)
  File "/Library/Python/2.7/site-packages/pip/utils/__init__.py", line 71, in ensure_dir
    os.makedirs(path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 1] Operation not permitted: '/System/Library/Frameworks/Python.framework/Versions/2.7/share'
Angads-MacBook-Pro:Downloads Angad$ cd gmusic-playlist-master
Angads-MacBook-Pro:gmusic-playlist-master Angad$ python ImportList.py ~/Desktop/Spotify.txt
Traceback (most recent call last):
  File "ImportList.py", line 8, in <module>
    from common import *
  File "/Users/Angad/Downloads/gmusic-playlist-master/common.py", line 5, in <module>
    from gmusicapi import Mobileclient
ImportError: No module named gmusicapi`

**Comment by angadchawla** [comment]
You know what, thank you for helping me. But I am too much of a noon to work this out. It would be better if I just did the transfer one song at a time. Thanks again!

**Comment by soulfx** [comment]
don't feel too bad. python throws everyone for loops. systems can come pre-installed with it, but the system manages the packages differently than what pip expects, or there can be multiple python versions on the system.  because of the differences it becomes a bit difficult to track down individual reasons for things not working.

the first time pip failed was due to it being unable to uninstall something called six, but the second time you tried pip you may not have run it with sudo.  you'll probably need to run sudo on the `python setup.py install` if you go that route.

i hope you don't have too many songs to import.  i wrote this import script after manually importing about 1k songs over the course of a couple hours.

**Comment by soulfx** [comment]
there is a javascript version you may be able to try out as an alternative to these python based scripts.  it can be found at https://github.com/soulfx/gmusic-playlist.js

**Comment by brett84c** [comment]
Oh, I spent several hours today, in vain, trying to get the Google Music API working.  I got my playlists and that data from [spotify-export](https://github.com/jlund/spotify-export), which was pretty easy, it was trying to install the 'gmusicapi' that was giving me serious issues.  Python was not working properly and kept giving me different errors, despite my efforts to download the proper packages and installing 'gmusicapi' through the downloaded git and running 'setup.py' in that directory.  Thank God I found this thread and saw you created the Javascript version.  It worked instantly for me.

If anyone at least has the necessary CSV files with the converted Spotify data, then I would highly recommend following the link soulfx put above [gmusic-playlist.js](https://github.com/soulfx/gmusic-playlist.js).  Much simpler process of importing to Google Music.

Much thanks, soulfx.  Do you take donations?

**Comment by soulfx** [comment]
Hi brett, thanks for sharing your experience, tips, and recommendation. The more positive feedback I hear about the javascript version the more I'll try to raise awareness about it.

Donations are accepted and much appreciated via my paypal account soulfx@yahoo.com

**Comment by angadchawla** [comment]
Thank you for all the help!
