### ISSUE TITLE
Playlist created, no songs

### ISSUE THREAD

**Issue by glasspear** [soulfx/gmusic-playlist#33]
I am having an odd problem - things seem to work ok, the log shows songs being match and a playlist being created.

When I check in GM when it is complete, there is indeed a playlist created, but the contents are empty.

I am using a 2FA account, with a generated password. Logs + CSV are in the attached zip, is there somewhere else I can look for error logs?

[playlist+log.zip](https://github.com/soulfx/gmusic-playlist/files/71804/playlist.log.zip)

**Comment by glasspear** [comment]
NM. forgot to put the trackNumber switch in for Rdio :)

**Comment by KurtTrowbridge** [comment]
Hi @glasspear, what's the "trackNumber switch" that you mentioned here? I'm attempting to import Rdio playlists as well and am also getting empty playlists. Is there something I need to change in the CSV they provided? Thanks!
