### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by Glecun** [soulfx/gmusic-playlist#42]
Hi,

I'm trying to to use the script with this command:
`python ExportLists.py playlists`

And i've this error:

> Traceback
 (most recent call last):
  File "ExportLists.py", line 4, in ?
    from common import *
  File "/home/gle/gmusic-playlist-master/gmusic-playlist-master/common.py", line 92
    if track.get('storeId') else track.get('id'))
     ^
SyntaxError: invalid syntax

Any ideas ?

Also, can I export all my music ? and not just all my playlists ?

Thanks in advance !

**Comment by soulfx** [comment]
All tracks will be exported as a playlist called 'all tracks' if configured to do so in preferences.

The line throwing the error is part of a ternary conditional starting from the previous line, try putting it all on one line and see if that helps.  are you using python 2.7?

**Comment by Glecun** [comment]
Ok :)

I installed python 2.7 and the error disappeared, 

Thank you
