### ISSUE TITLE
add exportLists ability to export entire library as playlist

### ISSUE THREAD

**Issue by soulfx** [soulfx/gmusic-playlist#7]
add ability to export entire library as a playlist to exportLists

**Comment by mgillespie** [comment]
I would love to see the script be able to match up locally available music on export and create a local playlist.

My main music is now Google Music, but for the car, it's USB...  keeping my playlists in sync is very time consuming (so it doesn't occur in reality).

I did start looking at this, by my python skills are not that good (I'm a .NET developer by day, and I don't do cross language very well!!!)

**Comment by soulfx** [comment]
addressed in 91c7ed3a4373972b619c3473acd0893a046c4b3c
