### ISSUE TITLE
Suggestion: Fall-back and remove "(...)" from name when searching

### ISSUE THREAD

**Issue by Daniel15** [soulfx/gmusic-playlist#9]
I used your `ImportList.py` script to import songs from Rdio into Google Play Music All Access, after using my own script to export from Rdio to CSV. It worked, great work! I had an issue with a few songs not being recognised because they had "(Radio Edit)" in the name on Rdio but not on Google Play. Would it be possible to edit the script to remove "(Radio Edit)" from the title when searching? I'd try to modify it my self but I don't know any Python :P

**Comment by soulfx** [comment]
added feature to 6a630df5973b185de27b95cc2fb4293a614e0f4d

**Comment by Daniel15** [comment]
Awesome, thanks!
